# Generated by Django 3.0.6 on 2020-09-09 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verified_email', models.BooleanField(default=False)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('home_number', models.CharField(blank=True, max_length=200, null=True)),
                ('firebaseToken', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, default='noimg.jpg', max_length=255, null=True, upload_to='avatars/%Y/%m')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'in_app'), (2, 'in_chat'), (3, 'in_background'), (4, 'offline')], default=1)),
                ('active_router', models.CharField(blank=True, max_length=200, null=True)),
                ('notificationOnOff', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Additional User Data',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(blank=True, max_length=200, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('os', models.CharField(blank=True, max_length=200, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_user_id', models.IntegerField(blank=True, null=True)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('fk_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AdditionalUserData')),
            ],
            options={
                'verbose_name_plural': 'Device',
            },
        ),
        migrations.CreateModel(
            name='Permission_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Owner', 'Owner'), ('Edit', 'Edit')], max_length=10)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_user_id', models.IntegerField(blank=True, null=True)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Permission type',
            },
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('verified_sim_code', models.CharField(blank=True, max_length=200, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_user_id', models.IntegerField(blank=True, null=True)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('fk_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sim',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=200, null=True)),
                ('row_id', models.IntegerField(blank=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_user_id', models.IntegerField(blank=True, null=True)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('fk_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_account', to=settings.AUTH_USER_MODEL)),
                ('fk_permission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_permission_type', to='accounts.Permission_type', verbose_name='fk_permission_type')),
            ],
            options={
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='M2M_Device_Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_account', models.IntegerField(blank=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_user_id', models.IntegerField(blank=True, null=True)),
                ('last_update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('id_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device')),
                ('id_sim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Sim')),
            ],
            options={
                'verbose_name_plural': 'M2M Device Sim',
            },
        ),
    ]
