# Generated by Django 3.0.6 on 2020-09-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200909_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluserdata',
            name='creation_timestamp',
        ),
        migrations.RemoveField(
            model_name='additionaluserdata',
            name='last_update_timestamp',
        ),
    ]
