# Generated by Django 3.0.6 on 2020-09-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200909_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserdata',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='additionaluserdata',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
