# Generated by Django 3.0.6 on 2020-09-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200909_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluserdata',
            name='creation_timestamp',
        ),
        migrations.RemoveField(
            model_name='additionaluserdata',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='additionaluserdata',
            name='last_update_timestamp',
        ),
        migrations.RemoveField(
            model_name='additionaluserdata',
            name='last_update_user_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='creation_timestamp',
        ),
        migrations.RemoveField(
            model_name='device',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_update_timestamp',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_update_user_id',
        ),
        migrations.RemoveField(
            model_name='m2m_device_sim',
            name='creation_timestamp',
        ),
        migrations.RemoveField(
            model_name='m2m_device_sim',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='m2m_device_sim',
            name='last_update_timestamp',
        ),
        migrations.RemoveField(
            model_name='m2m_device_sim',
            name='last_update_user_id',
        ),
        migrations.RemoveField(
            model_name='permission_type',
            name='creation_timestamp',
        ),
        migrations.RemoveField(
            model_name='permission_type',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='permission_type',
            name='last_update_timestamp',
        ),
        migrations.RemoveField(
            model_name='permission_type',
            name='last_update_user_id',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='creation_timestamp',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='last_update_timestamp',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='last_update_user_id',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='creation_timestamp',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='last_update_timestamp',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='last_update_user_id',
        ),
    ]
