# Generated by Django 3.0.6 on 2020-10-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200909_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaluserdata',
            old_name='notificationOnOff',
            new_name='notification',
        ),
    ]
